markdown: kramdown
permalink: /:title/
url: https://funricegenes.github.io/
name: funRiceGenes
author: Wen Yao (姚文)
qq: 1481758069
email: venyao@qq.com 
github: venyao
highlighter: rouge
safe: true
paginate: 20
about: "A comprehensive database of functionally characterized rice genes"
